base_url = "https://rukshanranasinghe2000.github.io/rukshan_portfolio/"
title = "Rukshan Ranasinghe"
compile_sass = false
build_search_index = false

[markdown]
[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
name = "Rukshan Ranasinghe"
alias = "Rukshan Ranasinghe"
email = "mailto:navodrukshan2000@gmail.com"
github = "https://github.com/RukshanRanasinghe2000"
linkedin = "https://www.linkedin.com/in/rukshan-ranasinghe-0a450036b/"
