base_url = "https://rukshan.se.com"
title = "Rukshan Ranasinghe"
compile_sass = false
build_search_index = false

[markdown]
[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
name = "Rukshan Ranasinghe"
alias = "Rukshan Ranasinghe"
email = "mailto:navodrukshan2000@gmail.com"
github = "https://github.com/RukshanRanasinghe2000"
